### ISSUE TITLE
Complex REST API queries

### ISSUE THREAD

**Issue by zikanl** [fasten-project/fasten#125]
There is a need for use cases within FASTEN project to execute "complex" queries on knowledge DB. These queries would return combined graph and metadata information per graph vertex (callable).  

Additional question to consider in this context is whether the client should have a number of API calls, and then to merge the results locally, or a single call would return JSON file that contains centrality measures, as well as quality and vulnerability metadata per callable ("enriched call graph"). Current hypothesis is that for graphs of relatively small size (up to 100K callables) it could be done locally.

**Comment by MihhailSokolov** [comment]
I am not sure if it's a good idea to switch back and forth between client and server computation depending on the graph size. It would make client-side code quite complex because it would need to first find out the size of the stitching graph (which would already require stitching on the server) and already then decide if it simply receives the graph or does the computation itself. I think that it is better to do the computation always on the server. @zikanl what do you think?

**Comment by zikanl** [comment]
I agree it would be ideal to do "everything" on the server, but, the generated graph could be large. That is why this has been suggested as an option. The other suggested option was to do all computation at the server (with lot of data generated) and then to use protocol buffer in order to efficiently transfer large chunks of data.

**Comment by MihhailSokolov** [comment]
> I agree it would be ideal to do "everything" on the server, but, the generated graph could be large. That is why this has been suggested as an option. The other suggested option was to do all computation at the server (with lot of data generated) and then to use protocol buffer in order to efficiently transfer large chunks of data.

I like the second option. Since projects tend to have a lot of transitive dependencies, I assume that a lot of stitched callgraphs will be quite big. So using protocol buffer seems like a nice idea. Anyway, we can still discuss this tomorrow during the meeting :)
