### ISSUE TITLE
REST API timeout

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#198]
## Describe the bug
Some of the requests result in the 504 Timeout even though they should be rather quick.
Example is the GET request to `https://api.fasten-project.eu/api/mvn/packages/com.amazonaws:aws-java-sdk-iotjobsdataplane/1.11.357/callables?limit=50`

**Comment by gousiosg** [comment]
This is clearly a problem with the database. The query that gets effectively executed is the following:

```sql
SELECT
	"public"."callables"."id",
	"public"."callables"."module_id",
	"public"."callables"."fasten_uri",
	"public"."callables"."is_internal_call",
	"public"."callables"."created_at",
	"public"."callables"."line_start",
	"public"."callables"."line_end",
	"public"."callables"."metadata"
FROM
	"public"."packages"
	JOIN "public"."package_versions" ON "public"."packages"."id" = "public"."package_versions"."package_id"
	JOIN "public"."modules" ON "public"."package_versions"."id" = "public"."modules"."package_version_id"
	JOIN "public"."callables" ON "public"."modules"."id" = "public"."callables"."module_id"
WHERE (TRUE
	AND lower("public"."packages"."package_name") = lower('com.amazonaws:aws-java-sdk-iotjobsdataplane')
	AND lower("public"."package_versions"."version") = lower('1.11.357'))
LIMIT 50 OFFSET 0;
```

I tried to run it through `EXPLAIN` to see what the optimiser thinks about it: [plan v1](https://explain.dalibo.com/plan/7YX)

It looks like the various joins are done using nested loops, which is not ideal. After searching the internetz, I found out about the `analyze` command. I have run it on all affected tables and the plan became more impressive: [plan v2](https://explain.dalibo.com/plan/1Zx). 

Unfortunately though, the query performance was not improved.

**Comment by gousiosg** [comment]
I 've tested this query on two instances of the same database, running on Postgres 12.2 (on `monster`) and 12.3 (on `lima`). `lima` has significantly less resources than `monster` and no SSDs. On 12.3, after running `ANALYZE`, the query returned instantly. 

Interestingly, the query plans were different [monster](https://explain.dalibo.com/plan/39o), [lima](https://explain.dalibo.com/plan/69a). It looks like 12.3 on `lima` uses the `unique_uri_call` index, but on `monster` it prefers to do a full table scan when joining `callables` with `modules`.

This indicates some issue with the query planner on 12.2, which should obviously use the index instead of sequentially scanning 15B rows. To confirm that I run `SET enable_seqscan=off` before the query on 12.2: amazingly the new query plan is exactly the same as for 12.3 (i.e., the index is used) and the query returns instantly.

We should upgrade to 12.3 (or even 13) soon.
