### ISSUE TITLE
mergeWithCHA() hides NullPointerExceptions

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#246]
In mergeWithCha()'s code, NullPointerExceptions thrown by the loop at lines 237-249 are hidden by the catch immediately afterwards:
```
        } catch (Exception e) {
            logger.error("Unable to fetch data from metadata database");
        }
```

Adding a report of the exception, as in
```
        } catch (Exception e) {
            logger.error("Unable to fetch data from metadata database", e);
        }
```
shows the following stack trace:
```
java.lang.NullPointerException: null
        at eu.fasten.core.merge.DatabaseMerger.resolve(DatabaseMerger.java:275)
        at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:245)
        at eu.fasten.core.search.SearchEngine.getStitchedGraph(SearchEngine.java:345)
        at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:625)
        at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:549)
        at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:534)
        at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:715)
```

For example, using the replication path of #231 (in particular, a backward search from commons-lang3) 46 such exception are generated. 

The exception interrupts the loop that builds the stitched graph, so the result will miss part of the arcs.

**Comment by proksch** [comment]
I think you are pointing at a problematic anti-pattern that we should fix as soon as possible.

1) This exception is swallowed.
2) The execution cannot be interrupted anymore (e.g., when rebalancing), because also `InterruptedExceptions` are caught.

I would suggest to break up the catch and use more specific exception types AND to replace or complement the `logger.error` call with a `throw new RuntimeException` (or maybe consider introducing a more specific subtype) to keep the signatures clean while not swallowing an exception...

Just returning `null` is poor handling, the proper handling should take place on a higher level, where some logic can actually decide to skip a certain analysis or to report an error and crash.

**Comment by proksch** [comment]
@ashkboos , @ilyagrishkov : Could you please look into this?

**Comment by ilyagrishkov** [comment]
> @ashkboos , @ilyagrishkov : Could you please look into this?

I'll take a look at it tomorrow

**Comment by vigna** [comment]
> I think you are pointing at a problematic anti-pattern that we should fix as soon as possible.

I fully agree—this wasn't easy to track down.

> Just returning `null` is poor handling, the proper handling should take place on a higher level, where some logic can actually decide to skip a certain analysis or to report an error and crash.

That's a good idea for the overall design, but the exception needs to be addressed, too. 

If you decide that it is ok for mergeWithCHA() to raise an exception, please specify under which conditions the exception is raised.

We think that the (hidden) exception under consideration is the result of some specific unintended bug in `mergeWithCHA()` that needs to be addressed in the method itself: currently, the call to `resolve()` at line 245 (next-to-last line of the stack dump) passes as fourth argument `typeMap.get(arc.source)`, which turns out to be `null`, but `resolve()` immediately invokes a method on that argument.

**Comment by ilyagrishkov** [comment]
> We think that the (hidden) exception under consideration is the result of some specific unintended bug in `mergeWithCHA()` that needs to be addressed in the method itself: currently, the call to `resolve()` at line 245 (next-to-last line of the stack dump) passes as fourth argument `typeMap.get(arc.source)`, which turns out to be `null`, but `resolve()` immediately invokes a method on that argument.

As rightly pointer out, the exception indeed comes from line 245 when typeMap  doesn't contain a key for a callable (e.g. ID -> FastenURI pair is missing) and it passes it to `resolve(...)` method. 
I have completely removed the try-catch that that was "hiding" exceptions from within the `resolve(...)` method and now instead of crashing if typeMap doesn't contain a certain callable I make one more attempt to fetch this specific callable from the database.

> If you decide that it is ok for mergeWithCHA() to raise an exception, please specify under which conditions the exception is raised.

In case typeMap doesn't contain a given callable and the following attempt to fetch it individually from the metadata database fails a RuntimeException is thrown. Alternatively I could change the implementation to not throw the exception and instead log the fact that a callable with this ID is missing and continue to the next arc, so that a call graph with at least some arcs is retuned.

**Comment by vigna** [comment]
I think we could coherently follow the current approach in GraphMavenResolver: have a property ignoreMissing that can be set to just ignore missing data (with a best-effort approach) or to throw an exception instead.

**Comment by ilyagrishkov** [comment]
> I think we could coherently follow the current approach in GraphMavenResolver: have a property ignoreMissing that can be set to just ignore missing data (with a best-effort approach) or to throw an exception instead.

That makes sense. I have added a try-catch  inside the loop in cabeefe. It is catching RuntimeExceptions after an attempt to retrieve it from the database was made and in case ignoreMissing is set to false throws it, or else continues to the next arc. All the changes are on develop

**Comment by proksch** [comment]
@ashkboos Is this issue still relevant? I would hope that during the major refactoring of the merge algorithm that took place over the summer, we got rid of these empty try/catch blocks? Please close this issue once you have reviewed the source code or link to the concrete places that are still in the merger code, waiting to be fixed.

**Comment by proksch** [comment]
I have opened a second PR to expose other problematic cases as well, but it seems that this concrete issue here has been resolved.
