### ISSUE TITLE
Docker: NPE running docker.pkg.github.com/fasten-project/fasten/fasten.server:latest

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#39]
Command: `$ ~/repos/fasten $ docker run --network="host" --log-opt max-size=1g -d docker.pkg.github.com/fasten-project/fasten/fasten.server:latest -k localhost:30001`

Log, NPE at line 255: 
[log.txt](https://github.com/fasten-project/fasten/files/4952738/log.txt)

**Comment by MagielBruntink** [comment]
OK, figured out that the docker hub images are not the ones to use. Sorry.

**Comment by wzorgdrager** [comment]
I noticed this error as well, but not in a Docker context. In general, if the arguments of the `fasten-server` jar are empty it will throw a NPE when launching a plugin. I think the shutdown should be more graceful. I'm also wondering what happens if a plugin does not require any command-line arguments.

**Comment by proksch** [comment]
I expect that this issue is been obsolete by now. Please feel free to re-open, should the problem reappear.
