### ISSUE TITLE
REST API contains hard coded path to vulnerable call chains cache

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#394]
## Describe the bug
At https://github.com/fasten-project/fasten/blob/14cd2eb01570e0d5e1a35c21bcfe0c3cb08d29d9/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/ResolutionApiServiceImpl.java#L194 there is a hardcoded string of the location of the vulnerable call chains cache. The REST API plugin has the `vc.path` property / parameter that should be used here, as suggested by the TODO in the line above.

**Comment by romatallinn** [comment]
@MagielBruntink thanks for raising the issue. This endpoint is from old implementation and is now depricated. Please use [VulnerableCallChainsAPI](https://github.com/fasten-project/fasten/blob/develop/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/VulnerableCallChainsApi.java) for the same logics, but using newer tools we have implemented. Sorry for confusion.

We are discussing what from the old implementation we want to remove and what to leave, because there are a few thing that can be still proved useful. @ashkboos and @mir-am have you decided anything on invalidation plugins? Do we want to leave the in tact for now? I guess I can safely remove old endpoint and processor plugin with no issues to not having confusing endpoints, right?
