### ISSUE TITLE
Recent changes to DB logic in server and plugins have broken the Quality Analyzer plugin

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#474]
## Describe the bug
Since recent changes to DB logic in the FASTEN server and plugins, the Quality Analyzer plugin has been broken. It runs into DataAccess exceptions when accessing the DB.

These are the relevant changes:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/3635696/173537600-36632fae-5ce8-4763-b59e-8565a6fb6d27.png">

## To Reproduce
1. Check out DC branch https://github.com/fasten-project/fasten-docker-deployment/tree/fasten-pipeline-release-0.0.9
2. Delete `docker-volumes/fasten`
3. `docker-compose --profile java up -d --build`
4. Browse to http://localhost:9080/api/mvn/packages/log4j:log4j/1.2.17
5. Observe the container log of fasten-docker-deployment-fasten-rapid-metadata-plugin-1 to see it run into DataAccess exceptions.

**Comment by mir-am** [comment]
Following the above steps, the Rapid plugin produces results to the `fasten.RapidPlugin.java.callable.priority.out` and it produced `5022` records by ingesting `log4j:log4j:1.2.17`. However, I also acknowledge that it gives `UnrecoverableError`, which is caused by `DataAccessException`. This means the plugin could not either query the DB or connect to it. So, our logic here is that the plugin should be restarted and try the input record again.
Previously, the plugin did not stop due to `DataAccessException` after 3 re-tries and hence it simply skips an input record.
If you do not like this behavior for the Rapid plugin, please feel free to revert this commit 29d20b9eee5ffd44a0c7420a56f3f7edc96db26c.

**Comment by mir-am** [comment]
> @mir-am these exception handling changes have actually brought to light a bug :-) in the quality analyzer. Fix incoming!

Ok, Interesting! :D
