### ISSUE TITLE
Nested "input" field in Kafka topic 'fasten.RepoCloner.out'

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#56]
The 'fasten.RepoCloner.out' topic has nested "input" field from its dependended topic 'fasten.POMAnalyser.out'. Should only include contents in the "payload" field from topic 'fasten.POMAnalyser.out'.

```
{
  "input": {
    "input": {
      "date": 1525962137,
      "groupId": "com.orientechnologies",
      "artifactId": "orientdb-studio",
      "version": "2.2.35"
    },
    "plugin_version": "0.1.0",
    ...
}
```

**Comment by ilyagrishkov** [comment]
This is by design. Every message includes the entire history of the pipeline. Hence the message of RepoCloner includes the entire output message of POMAnalyzer, which in term includes the Maven coordinate as its input.

It's an open issue for us, and we will be taking a second look at it. For now it doesn't break the code (the worst case scenario is messages becoming to big for Kafka, which can easily be avoided by writing plugin output to files). The matter will be further discussed after dealing with some other issues that currently require more attention.

**Comment by cg122** [comment]
Fair enough explanation, just did not see this in the 'Kafka Topics' wiki page. This design choice could also be documented there.

**Comment by ilyagrishkov** [comment]
Thanks for pointing it out. I'll document it on the wiki page.
